In [2]:
import numpy as np   
import pandas as pd

In [5]:
# MovieID::Title::Genres
movies = pd.read_csv("ml-1m/movies.dat", sep='::',header=None,
                     engine="python",encoding="latin-1" )
movies.columns=(["MovieID","Title","Genres"])

In [6]:
movies.head()

MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [8]:
users = pd.read_csv("ml-1m/users.dat", sep='::',header=None,
                     engine="python",encoding="latin-1" )
users.columns = ([ "UserID","Gender","Age","Occupation","Zip-code"])

In [10]:
users.head()

UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [12]:
# UserID::MovieID::Rating::Timestamp
ratings = pd.read_csv("ml-1m/ratings.dat", sep='::',header=None,
                     engine="python",encoding="latin-1" )
ratings.columns=(["UserID","MovieID","Rating","Timestamp"])

In [13]:
ratings.head()

UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [64]:
training_set = pd.read_csv("ml-100k/u2.base",delimiter="\t")
training_set.columns=(["UserID","MovieID","Rating","Timestamp"])
test_set = pd.read_csv("ml-100k/u2.test",delimiter="\t")
test_set.columns=(["UserID","MovieID","Rating","Timestamp"])

In [38]:
print("Number of Movies ",len(movies))
print("Number of Users ",len(users))
print("Number of Ratings ",len(ratings))
print("training_set size ",len(training_set))
print("test_set size",len(test_set))

Number of Movies  3883
Number of Users  6040
Number of Ratings  1000209
training_set size  79999
test_set size 19999


In [18]:
ratings.UserID.max()

6040

In [17]:
ratings[ratings.UserID < 100].groupby("UserID")["UserID"].count()

UserID
1     53
2    129
3     51
4     21
5    198
6     71
7     31
8    139
9    106
Name: UserID, dtype: int64

In [23]:
pd.merge(ratings[ratings.UserID ==4][["UserID","MovieID","Rating"]],movies,on="MovieID")

UserID  MovieID  Rating  \
0        4     3468       5   
1        4     1210       3   
2        4     2951       4   
3        4     1214       4   
4        4     1036       4   
5        4      260       5   
6        4     2028       5   
7        4      480       4   
8        4     1196       2   
9        4     1198       5   
10       4     1954       5   
11       4     1097       4   
12       4     3418       4   
13       4     3702       4   
14       4     2366       4   
15       4     1387       5   
16       4     3527       1   
17       4     1201       5   
18       4     2692       5   
19       4     2947       5   
20       4     1240       5   

                                                Title  \
0                                 Hustler, The (1961)   
1   Star Wars: Episode VI - Return of the Jedi (1983)   
2                        Fistful of Dollars, A (1964)   
3                                        Alien (1979)   
4                                     Die Hard (1988)   
5           Star Wars: Episode IV - A New Hope (1977)   
6                          Saving Private Ryan (1998)   
7                                Jurassic Park (1993)   
8   Star Wars: Episode V - The Empire Strikes Back...   
9                      Raiders of the Lost Ark (1981)   
10                                       Rocky (1976)   
11                  E.T. the Extra-Terrestrial (1982)   
12                             Thelma & Louise (1991)   
13                                     Mad Max (1979)   
14                                   King Kong (1933)   
15                                        Jaws (1975)   
16                                    Predator (1987)   
17             Good, The Bad and The Ugly, The (1966)   
18                   Run Lola Run (Lola rennt) (1998)   
19                                  Goldfinger (1964)   
20                             Terminator, The (1984)   

                                 Genres  
0                                 Drama  
1   Action|Adventure|Romance|Sci-Fi|War  
2                        Action|Western  
3         Action|Horror|Sci-Fi|Thriller  
4                       Action|Thriller  
5       Action|Adventure|Fantasy|Sci-Fi  
6                      Action|Drama|War  
7               Action|Adventure|Sci-Fi  
8     Action|Adventure|Drama|Sci-Fi|War  
9                      Action|Adventure  
10                         Action|Drama  
11      Children's|Drama|Fantasy|Sci-Fi  
12                         Action|Drama  
13                        Action|Sci-Fi  
14              Action|Adventure|Horror  
15                        Action|Horror  
16               Action|Sci-Fi|Thriller  
17                       Action|Western  
18                 Action|Crime|Romance  
19                               Action  
20               Action|Sci-Fi|Thriller

In [118]:
training_set = pd.read_csv("ml-100k/u1.base",delimiter="\t")
test_set = pd.read_csv("ml-100k/u1.test",delimiter="\t")
training_set_arr = np.array(training_set,dtype="int64")
test_set_arr = np.array(test_set,dtype="int64")
training_set.columns=(["UserID","MovieID","Rating","Timestamp"])
test_set.columns=(["UserID","MovieID","Rating","Timestamp"])
# 943 users  1682 movies

In [119]:
print(training_set_arr[:,0].max())
print(test_set_arr[:,0].max())
print("*"*50)
print(training_set_arr[:,1].max())
print(test_set_arr[:,1].max())

943
462
**************************************************
1682
1591


In [74]:
training_set_arr[:,1][training_set_arr[:,0]==1].shape

(134,)

In [75]:
len(training_set[training_set.UserID==1])

134

In [87]:
# all movie-id (index 1) for user 1

id_movies=training_set_arr[ training_set_arr[:,0]==1 , 1]

In [88]:
# all ratings (index 2) for user 1

id_ratings=training_set_arr[ training_set_arr[:,0]==1 , 2]

In [90]:
ratings = np.zeros(1682)

In [91]:
len(ratings)

1682

In [114]:
len(id_movies)

134

In [115]:
len(id_ratings)

134

In [116]:
len(ratings)

1682

In [96]:
ratings[id_movies-1]=id_ratings

In [100]:
ratings

array([0., 3., 4., ..., 0., 0., 0.])

In [110]:
arrmovies = np.array([1,2,3,4,5,6])
arrratings=np.array([5,4,3,2,5,1])
arrRatings = np.zeros(10)

In [111]:
arrRatings[arrmovies-1]=arrratings

In [112]:
arrRatings

array([5., 4., 3., 2., 5., 1., 0., 0., 0., 0.])

In [124]:
def convert(data):
    new_data=[]
    for id_user in range(1,943+1):
        id_movies = data[data[:,0]==id_user, 1] # watched movie-id for that user in id_user
        id_ratings = data[data[:,0]==id_user,2] # ratings for the watched movies for that user in id_user
        ratings = np.zeros(1682)  # matrix, ratings for all 1682 movies watched as well as not watched ,filled with zero
        # overlap ratings for viewed moves and not viewed keep it zero
        #id_movies-1 ensures that we use index 0 also
        ratings[id_movies-1] = id_ratings
        new_data.append(list(ratings))
    return new_data

In [125]:
training_set_list=convert(training_set_arr)    
test_set_list=convert(test_set_arr)    


In [126]:
import torch

In [129]:
training_set_tensor=torch.FloatTensor(training_set_list)

In [130]:
type(training_set_tensor)

torch.Tensor

In [131]:

len(training_set_tensor)

943

In [132]:
training_set_tensor

tensor([[0., 3., 4.,  ..., 0., 0., 0.],
        [4., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [5., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 5., 0.,  ..., 0., 0., 0.]])

In [1]:
import torch

In [11]:
nv=5
nh=10
Weights = torch.randn(nv,nh)
biasHidden = torch.randn(1,nh)
biasVisible = torch.randn(1,nv)
x=torch.randn(1,nv)

In [19]:
Weights.shape

torch.Size([5, 10])

In [20]:
Weights.t().shape

torch.Size([10, 5])

In [4]:
biasHidden

tensor([[-0.1762, -0.6697,  0.3977, -0.9644, -0.8052, -0.9961,  0.2134,  0.7723,
          0.2737, -0.6121]])

In [5]:
biasVisible

tensor([[-0.5822,  0.5828, -1.2561, -0.3028,  0.8640]])

In [7]:
x

tensor([-0.5068,  0.0124, -0.5114, -0.3332,  0.0517])

In [13]:
wx = torch.mm(x,Weights)

In [14]:
wx

tensor([[ 0.7728, -2.3043,  1.1653, -0.1526,  1.9217,  0.5909,  1.0379,  1.6596,
          0.4416, -1.4493]])

In [15]:
x.shape

torch.Size([1, 5])

In [16]:
Weights.shape

torch.Size([5, 10])

In [23]:
nb_users = 943
batch_size=100

for id_users in range(0,nb_users-batch_size,batch_size):
    print(id_users)

0
100
200
300
400
500
600
700
800
900
